#
# Copyright (c) 2020 INESC TEC <https://www.inesctec.pt>
#
# This Source Code Form is subject to the terms of the European Union
# Public License, v. 1.2. If a copy of the EUPL was not distributed with
# this file, You can obtain one at https://opensource.org/licenses/EUPL-1.2.
#
# SPDX-License-Identifier: EUPL-1.2
#

name: Android Check Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: Cache npm dependencies
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install npm dependencies
        run: |
          yarn --ignore-scripts
          yarn postinstall_android

      - name: Setup environment
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570"
          echo "${{secrets.ENV_PRODUCTION_STAGING}}" > android/.env
          echo "${{secrets.GOOGLE_SERVICE_PRODUCTION_STAGING}}" > android/app/src/productionStaging/google-services.json
          echo "${{secrets.ANDROID_KEYSTORE}}" > divoc.keystore.asc
          gpg -d --passphrase '${{secrets.ANDROID_KEYSTORE_PASSWORD}}' --batch divoc.keystore.asc > android/app/divoc.keystore

      - name: Build ABB
        run: |
          cd android
          ./gradlew bundleProductionStaging \
            -PkeystoreFile="$GITHUB_WORKSPACE/android/app/divoc.keystore" \
            -PkeystorePassword="${{secrets.KEYSTORE_PASSWORD}}" \
            -PkeyAlias="divoc.release.key" \
            -PkeyPassword="${{secrets.KEY_PASSWORD}}"

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleProductionStaging \
            -PkeystoreFile="$GITHUB_WORKSPACE/android/app/divoc.keystore" \
            -PkeystorePassword="${{secrets.KEYSTORE_PASSWORD}}" \
            -PkeyAlias="divoc.release.key" \
            -PkeyPassword="${{secrets.KEY_PASSWORD}}"

      - name: Upload AAB
        uses: actions/upload-artifact@v2
        with:
          name: app-production-staging.aab
          path: android/app/build/outputs/bundle/productionStaging/app-production-staging.aab

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-production-staging.apk
          path: android/app/build/outputs/apk/production/staging/app-production-staging.apk

      - name: Upload Mapping File
        uses: actions/upload-artifact@v2
        with:
          name: mapping.text
          path: android/app/build/outputs/mapping/productionStaging/mapping.txt
